### ISSUE TITLE
Problem with path in driver file when put folder and filename together

### ISSUE THREAD

**Issue by brunopiaui** [andreluzz/cas-xog#15]
When I try to read a lookup, for example, and I put a folder with the filename on the path, the cas-xog don't return error message, make a folder "Lookups" in "_read / _write" folders but don't create the result file.

`<?xml version="1.0" encoding="utf-8"?>`
`<xogdriver version="2.0">`
`  <lookup code="CMN_CONTENT_SOURCES" path="common/Lookups/CMN_CONTENT_SOURCES.xml" />`
`</xogdriver>`

**Comment by andreluzz** [comment]
Resolved including driver full path when creating folders structure.
